---
- hosts: localhost
  become: yes
  tasks:
  ### Apps
    - name: Install useful apps
      package:
        name: 
          - curl
          - flatpak
          - git
          - neofetch
        state: present

  ### Flatpak and Flathub apps
    - name: Enable Flathub repository
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present
    - name: Install Favorite Flatpack Apps
      flatpak:
        name: 
          - com.dropbox.Client
          - org.signal.Signal
          - com.github.micahflee.torbrowser-launcher
          - org.libreoffice.LibreOffice
          - org.gnome.Totem
          - org.gnome.Calculator
          - org.gnome.Cheese
          - org.remmina.Remmina
          - com.visualstudio.code
          - de.haeckerfelix.Fragments
          - org.gnome.eog
          - org.gnome.Evince
          - org.mozilla.firefox
          - com.mattjakeman.ExtensionManager
        state: present 
  ### Remove apps
    - name: Remove Gnome Apps
      package: 
        name: 
          - gnome-maps
          - gnome-weather
          - gnome-boxes
          - gnome-calendar
          - cheese
          - gnome-clocks
          - gnome-calculator
          - gnome-characters
          - gnome-connections
          - gnome-contacts
          - gnome-font-viewer
          - gnome-logs
          - baobab
          - simple-scan
          - rhythmbox
          - totem
        state: absent
    - name: Gnome Tour
      package: 
        name: gnome-tour
        state: absent 
    - name: Yelp 
      package: 
        name: yelp
        state: absent
    - name: Image Viewer 
      package: 
        name: eog
        state: absent
    - name: Remove Fedora Media Writer
      package: 
        name: mediawriter
        state: absent
    - name: Libreoffice 
      package: 
        name: libreoffice-core
        state: absent
    - name: Firefox 
      package: 
        name: firefox
        state: absent
    - name: Language that not useful 
      package: 
        name: 
          - libzhuyin
          - libpinyin
        state: absent
        
    # - name: Enable Night Light
    #   dconf:
    #     key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
    #     value: 'true'
    # - name: Set Night Light Temperature
    #   dconf:
    #     key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
    #     value: uint32 5500